// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `NaijaFarmerDBConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost;initial catalog=NaijaFarmerDB;User ID=sa;Password=******; Integrated Security=true`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace NaijaFarmers.DAL.Models
{
    /// <summary>
    /// A class which represents the __EFMigrationsHistory table.
    /// </summary>
	[Table("__EFMigrationsHistory")]
	public partial class EFMigrationsHistory
	{
		[Key]
		public virtual string MigrationId { get; set; }
		public virtual string ProductVersion { get; set; }
	}

}
