// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `LeaveApplicationDBConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=DESKTOP-KG7SLVL;initial catalog=LeaveApplicationDB;Integrated Security=true`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace LeaveApplication.DAL.Models
{
    /// <summary>
    /// A class which represents the __EFMigrationsHistory table.
    /// </summary>
	[Table("__EFMigrationsHistory")]
	public partial class EFMigrationsHistory
	{
		[Key]
		public virtual string MigrationId { get; set; }
		public virtual string ProductVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the StaffInformation table.
    /// </summary>
	[Table("StaffInformation")]
	public partial class StaffInformation
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string StaffId { get; set; }
		public virtual string LineManager { get; set; }
		public virtual int? LeaveBalance { get; set; }
	}

}
